apiVersion: v1
kind: Service
metadata:
  name: {{ include "masa-protocol.fullname" . }}
  labels:
    {{- include "masa-protocol.labels" . | nindent 4 }}
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - port: 4001
      targetPort: 4001
      protocol: UDP
      name: udpconnection
  selector:
    {{- include "masa-protocol.selectorLabels" . | nindent 4 }}
