/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as oracleNodeStakingContractSol from "./OracleNodeStakingContract.sol";
export type { oracleNodeStakingContractSol };
export type { Lock } from "./Lock";
export type { MasaToken } from "./MasaToken";
