package config

const (
	PrivKeyFile = "MASA_PRIV_KEY_FILE"
	BootNodes   = "BOOTNODES"
	MasaDir     = "MASA_DIR"
	RpcUrl      = "RPC_URL"
	PortNbr     = "PORT_NBR"
	UDP         = "UDP"
	TCP         = "TCP"
	PrivateKey  = "PRIVATE_KEY"
	StakeAmount = "STAKE_AMOUNT"
	LogLevel    = "LOG_LEVEL"
	LogFilePath = "LOG_FILEPATH"
	Environment = "ENV"
	AllowedPeer = "allowedPeer"
	Signature   = "signature"
	Debug       = "debug"
	FilePath    = "FILE_PATH"
	Validator   = "VALIDATOR"
	CachePath   = "CACHE_PATH"
	Faucet      = "FAUCET"

	OracleProtocol       = "oracle_protocol"
	WorkerProtocol       = "worker_protocol"
	NodeDataSyncProtocol = "nodeDataSync"
	NodeGossipTopic      = "gossip"
	PublicKeyTopic       = "bootNodePublicKey"
	WorkerTopic          = "workerTopic"
	BlockTopic           = "blockTopic"
	Rendezvous           = "masa-mdns"
	PageSize             = 25

	TwitterUsername    = "TWITTER_USERNAME"
	TwitterPassword    = "TWITTER_PASSWORD"
	Twitter2FaCode     = "TWITTER_2FA_CODE"
	DiscordBotToken    = "DISCORD_BOT_TOKEN"
	TwitterScraper     = "TWITTER_SCRAPER"
	DiscordScraper     = "DISCORD_SCRAPER"
	TelegramScraper    = "TELEGRAM_SCRAPER"
	WebScraper         = "WEB_SCRAPER"
	APIEnabled         = "API_ENABLED"
	APIListenAddress   = "API_LISTEN_ADDRESS"
	ProxyEnabled       = "PROXY_ENABLED"
	DefaultPrivKeyFile = "masa_oracle_key"
)
